### ISSUE TITLE
I did not find the crucial Deterministically select the oldest/best masternode to pay on the network

### ISSUE THREAD

**Issue by luomijie** [HashEngineering/dashj#13]
I did not find the key content of the MasternodePayment part of the DASH core project, including Deterministically select the oldest/best masternode to pay on the network.Is it because it is not implemented? Or it still exists, but I did not find it?

**Comment by HashEngineering** [comment]
That part is not implemented.

We are currently working on the masternode messages and objects that will possible later allow for PrivateSend functionality.  MasternodePayments is not in the current plan.

The main point of this repo is to support a few mobile apps, primarily Dash Wallet for android.  That doesn't mean we cannot include other functionality from Dash Core.  We welcome pull requests.
