### ISSUE TITLE
Problems when try to execute mvn clean install -DskipTests on MAC

### ISSUE THREAD

**Issue by rafaelje** [HashEngineering/dashj#15]
```
Software:

    System Software Overview:

      System Version: macOS 10.13.4 (17E199)
      Kernel Version: Darwin 17.5.0
```

Steps to reproduce

```
$ git clone https://github.com/HashEngineering/dashj.git

$ cd dashj

$ git checkout release-0.14

$ mvn clean install -DskipTests
```

at this point I got an error with this file `core/src/main/java/org/bitcoinj/core/MasterNode.java` the name of the file is capitalized and should be `Masternode.java`

after rename it works fine 👍

**Comment by HashEngineering** [comment]
We haven't updated the release-0.14 branch in over a year, but we should have because it is still under active development.

master and release-0.14 are now the same.
